# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_deploy:
  steps:
    - checkout
    - save_cache:
        name: Saving repo cache
        key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - .
    - run:
        name: npm dependency install
        command: |
          npm set unsafe-perm true
          npm install
    - run: aws s3 sync ./app/build/ s3://Roman_Romanov

workflows:
  version: 2
